add description for raspberry pi switch
SpaceApi/website pull request #116
Opened 2022-08-04 11:35 UTC by niccokunzmann

I added our Raspberry Pi switch to this so that other people can build on top of it. Maybe they will improve it and I can make mine better :)
There is a documentation about how to fork and setup. It is quite easy.

2022-08-04 22:08 UTC, niccokunzmann commented
Hm. How would I put that here? https://spaceapi.io/provide-an-endpoint/#stuff-you-can-use

2022-08-05 10:50 UTC, dbrgn commented
> Hm. How would I put that here? https://spaceapi.io/provide-an-endpoint/#stuff-you-can-use

Yeah, it probably makes sense to put it into the `operation` category, not `space-visualization`!

2022-08-05 10:51 UTC, dbrgn requested changes

2022-08-05 10:51 UTC, dbrgn commented on content/stuff/raspberry-pi-button/contents.lr
> +description: This provides source code and a directory endpoint for the hackerspace status baes on a Raspberry Pi attached to a button. You can switch the space on and off.
```suggestion
description: This provides source code and a directory endpoint for the hackerspace status based on a Raspberry Pi attached to a button. You can switch the opening status on and off.
```

2022-08-05 10:51 UTC, dbrgn commented on content/stuff/raspberry-pi-button/contents.lr
> +category: space-visualization
```suggestion
category: operation
```

2022-08-05 15:38 UTC, niccokunzmann commented
@dbrgn, I merged the suggestions. Thanks!

2022-08-07 16:51 UTC, merged